language: go

go:
  - 1.9
  - "1.10"
  - master

matrix:
  fast_finish: true
  allow_failures:
    - go: master

install:
  - go get -u github.com/golang/lint/golint
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - cat ./adjectives.txt | perl ./isAlphabetized.pl
  - cat ./nouns.txt | perl ./isAlphabetized.pl
  - go test -v ./...
  - golint ./...
